export const INDIAN_STATES = [
  { code: 'AP', label_en: 'Andhra Pradesh', label_hi: 'आंध्र प्रदेश' },
  { code: 'AS', label_en: 'Assam', label_hi: 'असम' },
  { code: 'BR', label_en: 'Bihar', label_hi: 'बिहार' },
  { code: 'CT', label_en: 'Chhattisgarh', label_hi: 'छत्तीसगढ़' },
  { code: 'DL', label_en: 'Delhi', label_hi: 'दिल्ली' },
  { code: 'GJ', label_en: 'Gujarat', label_hi: 'गुजरात' },
  { code: 'HR', label_en: 'Haryana', label_hi: 'हरियाणा' },
  { code: 'HP', label_en: 'Himachal Pradesh', label_hi: 'हिमाचल प्रदेश' },
  { code: 'JH', label_en: 'Jharkhand', label_hi: 'झारखंड' },
  { code: 'KA', label_en: 'Karnataka', label_hi: 'कर्नाटक' },
  { code: 'KL', label_en: 'Kerala', label_hi: 'केरल' },
  { code: 'MP', label_en: 'Madhya Pradesh', label_hi: 'मध्य प्रदेश' },
  { code: 'MH', label_en: 'Maharashtra', label_hi: 'महाराष्ट्र' },
  { code: 'OR', label_en: 'Odisha', label_hi: 'ओडिशा' },
  { code: 'PB', label_en: 'Punjab', label_hi: 'पंजाब' },
  { code: 'RJ', label_en: 'Rajasthan', label_hi: 'राजस्थान' },
  { code: 'TN', label_en: 'Tamil Nadu', label_hi: 'तमिल नाडु' },
  { code: 'TS', label_en: 'Telangana', label_hi: 'तेलंगाना' },
  { code: 'UP', label_en: 'Uttar Pradesh', label_hi: 'उत्तर प्रदेश' },
  { code: 'UK', label_en: 'Uttarakhand', label_hi: 'उत्तराखंड' },
  { code: 'WB', label_en: 'West Bengal', label_hi: 'पश्चिम बंगाल' },
];
